CREATE TABLE drivers (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      organization_id UUID NOT NULL REFERENCES organizations(id),
      full_name VARCHAR(255),
      date_of_birth DATE,
      contact_number VARCHAR(20),
      email_address VARCHAR(255),
      residential_address TEXT,
      license_number VARCHAR(255),
      license_expiration_date DATE,
      license_class VARCHAR(255),
      endorsements TEXT,
      employment_start_date DATE,
      employment_end_date DATE,
      emergency_contact_name VARCHAR(255),
      emergency_contact_number VARCHAR(20),
      medical_certifications TEXT,
      certification_expiration_date DATE,
      training_completed TEXT,
      assigned_vehicle_id UUID REFERENCES vehicles(id),
      performance_score DECIMAL,
      accident_history TEXT,
      violation_history TEXT,
      availability_status VARCHAR(255),
      shift_preferences VARCHAR(255),
      notes TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
