CREATE TABLE loads (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      organization_id UUID NOT NULL REFERENCES organizations(id),
      vehicle_id UUID REFERENCES vehicles(id),
      driver_id UUID REFERENCES drivers(id),
      load_reference_number VARCHAR(255),
      origin_address TEXT,
      origin_contact_information TEXT,
      destination_address TEXT,
      destination_contact_information TEXT,
      pickup_date_time TIMESTAMPTZ,
      delivery_date_time TIMESTAMPTZ,
      equipment_type_required VARCHAR(255),
      commodity_description TEXT,
      load_status VARCHAR(255),
      assigned_driver TEXT,
      carrier_information TEXT,
      rate_freight_charge DECIMAL,
      fuel_surcharge DECIMAL,
      accessorial_charges DECIMAL,
      total_payment_due DECIMAL,
      payment_status VARCHAR(255),
      special_instructions TEXT,
      document_links TEXT,
      mileage DECIMAL,
      load_board_posting_status VARCHAR(255),
      broker_shipper_details TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
