CREATE TABLE vehicles (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      organization_id UUID NOT NULL REFERENCES organizations(id),
      vin VARCHAR(255) UNIQUE,
      license_plate_number VARCHAR(255),
      license_expiration_date DATE,
      insurance_expiration_date DATE,
      make VARCHAR(255),
      model VARCHAR(255),
      year_of_manufacture INTEGER,
      color VARCHAR(255),
      fuel_type VARCHAR(255),
      fuel_capacity DECIMAL,
      fuel_economy DECIMAL,
      odometer_reading DECIMAL,
      engine_size_and_type VARCHAR(255),
      transmission_type VARCHAR(255),
      purchase_date DATE,
      purchase_price DECIMAL,
      ownership_status VARCHAR(255),
      operating_status VARCHAR(255),
      assigned_driver UUID REFERENCES drivers(id),
      maintenance_schedule DATE,
      last_maintenance_date DATE,
      next_maintenance_due DATE,
      warranty_expiration_date DATE,
      insurance_policy_number VARCHAR(255),
      insurance_provider VARCHAR(255),
      tire_specifications VARCHAR(255),
      cargo_capacity DECIMAL,
      gps_tracking_enabled BOOLEAN,
      telematics_device_id VARCHAR(255),
      depreciation_value DECIMAL,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
